tau32-ddk.c: suppress warning about ignored attributes
This driver is heavily obfuscated, and causes a -Werror warning with
clang 18 now:

  sys/dev/ce/tau32-ddk.c:358:10: error: 'const' attribute on function returning 'void'; attribute ignored [-Werror,-Wignored-attributes]
    358 | ((const))nvqbt(void){__asm __volatile("repe; nop; repe; nop;"
        |          ^

Supress the warning since the driver can never be fixed. Direct commit
to stable/13, since the driver has been removed in 14.x and later.

PR:		276104