ngatm: Fix mismatches between function definitions and prototypes
This is a direct commit to stable/13 (ngatm was removed in 14.0) to
fix warnings reported by GCC 13 such as:

/freebsd/stable/13/sys/contrib/ngatm/netnatm/sig/sig_reset.c:82:1: error: conflicting types for 'uni_sig_start' due to enum/integer mismatch; have 'void(struct uni *, u_int,  uint32_t,  struct uni_msg *, struct uni_all *)' {aka 'void(struct uni *, unsigned int,  unsigned int,  struct uni_msg *, struct uni_all *)'} [-Werror=enum-int-mismatch]
   82 | uni_sig_start(struct uni *uni, u_int sig, uint32_t cookie,
      | ^~~~~~~~~~~~~
In file included from /freebsd/stable/13/sys/contrib/ngatm/netnatm/sig/sig_reset.c:40:
/freebsd/stable/13/sys/contrib/ngatm/netnatm/sig/unipriv.h:257:6: note: previous declaration of 'uni_sig_start' with type 'void(struct uni *, enum start_sig,  uint32_t,  struct uni_msg *, struct uni_all *)' {aka 'void(struct uni *, enum start_sig,  unsigned int,  struct uni_msg *, struct uni_all *)'}
  257 | void uni_sig_start(struct uni *, enum start_sig, uint32_t cookie,
      |      ^~~~~~~~~~~~~

Reported by:	GCC -Wenum-int-mismatch