sound tests: Fix gcc build
/workspace/src/tests/sys/sound/pcm_read_write.c:36:1: error: 'static' is not
at beginning of declaration [-Werror=old-style-declaration]
   36 | } static const afmt_tests[] = {
      | ^

Reported by:	CI
Fixes:		27ef5d48c729 ("sound: Unit test the pcm sample read and write macros")
Sponsored by:	The FreeBSD Foundation
MFC after:	1 week

(cherry picked from commit f6631da0b581b28c2bfeea1199b52013bb46aa41)